language: node_js
node_js:
  - '14'
addons:
  chrome: stable
branches:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
      - hspichardo@gmail.com
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    branch: master
  app: toberumanapi

